### ISSUE TITLE
Seed parsing

### ISSUE THREAD

**Issue by Cherry** [nodecraft/customer-suggestions#12]
Certain seeds for Minecraft servers are still parsed incorrectly and malformed in this process on server start due to the methods of parsing we use internally.

**Comment by Cherry** [comment]
Issue resolved, pending distribution to all devices.

**Comment by blazedd** [comment]
This needs to be addressed with issue #5 before pushed.

**Comment by blazedd** [comment]
This issue was solved several updates ago and was never closed. Whoops!
